### ISSUE TITLE
Error during convertion: undefined is not a valid argument for URI

### ISSUE THREAD

**Issue by robogeek** [lucybot/api-spec-converter#103]
First - isn't the error message misspelled?  Oh, but that error message is from URI.js.  

I'm filing the issue here because api-spec-converter is sending `undefined` into URI.js.

When trying to convert a WADL to Swagger2 I'm getting this error:

```
$ api-spec-converter --to swagger_2 --from wadl sep_wadl.xml 
Fatal TypeError: Error during convertion: undefined is not a valid argument for URI
    at new URI (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/urijs/src/URI.js:54:15)
    at URI (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/urijs/src/URI.js:46:16)
    at convertToSwagger (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/lib/formats/wadl.js:290:17)
    at /Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/lib/formats/wadl.js:20:28
    at tryCatcher (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/bluebird/js/release/method.js:15:34
    at /Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/lib/base_format.js:105:12
    at tryCatcher (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/bluebird/js/release/method.js:39:29)
    at BaseFormat.resolveSubResources.Promise.map.BaseFormat.parse.BaseFormat.readSpec.BaseFormat.resolveResources.BaseFormat.convertTo.Promise.try [as convertTo] (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/lib/base_format.js:97:21)
    at /Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/index.js:33:32
    at tryCatcher (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/david/Laplace/ZigBee/docs-13-0201-00-sep-2-uml-model-xsd-wadl/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:685:18)
```

I did a little investigation and did a little modification:

```
if (typeof root.$.base === 'undefined') {
    console.error('UNDEFINED root.$.base');
    console.error(util.inspect(root));
}
  var baseUrl = URI(root.$.base);
```

The data output from the util.inspect shows the `root.$` object has a `resource` object but not a `base` object.

The WADL is the SEP2 WADL from ZigBee which can be retrieved for free from here:  http://www.zigbee.org/zigbee-for-developers/applicationstandards/zigbee-2030-5/

**Comment by IvanGoncharov** [comment]
> The WADL is the SEP2 WADL from ZigBee which can be retrieved for free from here:

@robogeek Can you please post a direct link or attach the file.

> The data output from the util.inspect shows the root.$ object has a resource object but not a base object.

According to [WADL spec](https://www.w3.org/Submission/wadl/#x3-110002.5):
```
A resources element has a base attribute of type xsd:anyURI that provides the base URI for each child resource identifier
```
According to [Swagger spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields):
```
If the host is not included, the host serving the documentation is to be used (including the port).
```
So if we don't add any host in Swagger file it will confuse tooling.

A possible workaround would be to manually add `base` attribute.

On our side, we need to improve error reporting.

**I didn't have a file to investigate so following analysis made based on your comment.
I still want to look at it, because it may have simular attribute under different name.**

**Comment by robogeek** [comment]
Okay, there doesn't seem to be a license attached to the file, so it's okay to share it here it seems.  The .zip archive has both the sep_wadl.xml and corresponding sep.xsd

[Archive 2.zip](https://github.com/lucybot/api-spec-converter/files/400115/Archive.2.zip)

**Comment by IvanGoncharov** [comment]
@robogeek Thanks for attaching archive it allowed me to browse through the file.
I found that ZigBee uses their own vendor extensions: `xmlns:wx="http://zigbee.org/wadlExt"`.
According to [this issue](https://community.smartbear.com/t5/SoapUI-Open-Source/NullPointer-importing-XML-validated-WADL-file/td-p/25696):
>This is because this WADL is intended to serve as normative guidance, with manufacturers first needing to transform the "wx:" elements and attributed to WADL equivalents.

So you need to do above transformation before doing a conversion.

**Comment by robogeek** [comment]
Hm, thank you for the advice.  This is my first time doing anything with WADL so I've got some things to learn ... did some remedial reading today, and I've got an inkling of what you said to do.

**Comment by IvanGoncharov** [comment]
@robogeek  I'm glad I could help 😄
