### ISSUE TITLE
Syntax Error: Unexpected token

### ISSUE THREAD

**Issue by maneeshsahu** [lucybot/api-spec-converter#108]
I am getting this error when I use api-spec-converter to convert from swagger_1 to swagger_2

`/usr/local/lib/node_modules/api-spec-converter/index.js:33
    .then(fromSpec => fromSpec.convertTo(options.to))
                   ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:445:25)
    at Object.Module._extensions..js (module.js:480:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:367:17)
    at require (module.js:386:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/api-spec-converter/bin/api-spec-converter:8:17)
    at Module._compile (module.js:462:26)
    at Object.Module._extensions..js (module.js:480:10)`

**Comment by IvanGoncharov** [comment]
@maneeshsahu Do you use it in browser on node.js?
If node can you please provide output of: `node --version`?
It should be newer that `4.2.0`, see this:
https://github.com/lucybot/api-spec-converter/blob/master/package.json#L5

**Comment by IvanGoncharov** [comment]
@maneeshsahu Can you please provide requested details?
without them we can't fix this bug.

**Comment by maneeshsahu** [comment]
Hi @IvanGoncharov 
This is my version of node
`~ $ node -v
v0.13.0-pre`

**Comment by IvanGoncharov** [comment]
@maneeshsahu You need to update node to at least `4.2.0`.
We drop support for node `v0.xx` since version `2.0.0` of this lib.

**Comment by maneeshsahu** [comment]
I was upgrading using brew and it just wasn't updating the node version. I just downloaded the binary for OS X and that fixed the issue. Thank you!
