### ISSUE TITLE
Unable to convert this swagger_docs to wadl

### ISSUE THREAD

**Issue by jvaidyaa** [lucybot/api-spec-converter#117]
https://api.qat.obi.aol.com/biz/v2/api-docs/

**Comment by jvaidyaa** [comment]
{"cause":{},"isOperational":true}
Open an issue on GitHub

**Comment by bobby-brennan** [comment]
Are you using the online converter, or the command-line tool?  The command-line version seems to have more success with WADL.

**Comment by jvaidyaa** [comment]
I tried both, the command line give the following error, this error itself was for the online converter, but the error for the command line is as below
us158999:~ jvaidyaa$ api-spec-converter https://api.qat.obi.aol.com/biz/v2/api-docs/ --from=swagger_1 --to=wadl > obi.wadl
Fatal Error: Incorrect format
    at Error (native)
    at readSpec.spread (/usr/local/lib/node_modules/api-spec-converter/lib/base_format.js:78:15)
    at tryCatcher (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:507:35)
    at Promise._settlePromise (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise_array.js:143:14)
    at PromiseArray._iterate (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise_array.js:113:31)
    at PromiseArray.init [as _init] (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise_array.js:77:10)
    at Promise._settlePromise (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/local/lib/node_modules/api-spec-converter/node_modules/bluebird/js/release/async.js:133:16)

**Comment by bobby-brennan** [comment]
Sorry, I misread the title, I though you were trying to convert WADL to Swagger.

Currently we only support conversion **to** Swagger:
https://github.com/lucybot/api-spec-converter#conversion-table

Would happily accept a PR that adds Swagger -> WADL support though. Wouldn't be too hard to reverse the logic in `lib/formats/wadl.js`.
