### ISSUE TITLE
TypeError: Error during convertion: Cannot read property 'resources' of undefined

### ISSUE THREAD

**Issue by nagromc** [lucybot/api-spec-converter#83]
Hi,

I have an error when I run the following code:

```js
var Converter = require('api-spec-converter');

Converter.convert({
    from: 'wadl',
    to: 'swagger_2',
    source: 'http://localhost:9080/rest/application.wadl'
}, function(err, converted) {
    console.trace(err);
});
```

Here is the stack trace:

    Trace: [TypeError: Error during convertion: Cannot read property 'resources' of undefined]
        at L:\mcourbet\dev\git\plq\plq-parent\plq-web\gulpfile.js:54:17
        at L:\mcourbet\dev\git\plq\plq-parent\plq-web\node_modules\api-spec-converter\lib\base-type.js:133:14
        at converters.swagger_2 (L:\mcourbet\dev\git\plq\plq-parent\plq-web\node_modules\api-spec-converter\lib\types\wadl.js:20:14)
        at BaseType.convertTo (L:\mcourbet\dev\git\plq\plq-parent\plq-web\node_modules\api-spec-converter\lib\base-type.js:130:3)
        at L:\mcourbet\dev\git\plq\plq-parent\plq-web\node_modules\api-spec-converter\index.js:37:14
        at L:\mcourbet\dev\git\plq\plq-parent\plq-web\node_modules\api-spec-converter\index.js:17:7
        at null.<anonymous> (L:\mcourbet\dev\git\plq\plq-parent\plq-web\node_modules\api-spec-converter\lib\base-type.js:117:7)
        at null.<anonymous> (L:\mcourbet\dev\git\plq\plq-parent\plq-web\node_modules\api-spec-converter\lib\base-type.js:47:7)
        at L:\mcourbet\dev\git\plq\plq-parent\plq-web\node_modules\async\lib\async.js:52:16
        at L:\mcourbet\dev\git\plq\plq-parent\plq-web\node_modules\async\lib\async.js:361:13

The WADL:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<a:application xmlns:a="http://wadl.dev.java.net/2009/02"><a:doc xmlns:b="http://jersey.java.net/" b:generatedBy="Jersey: 1.19 02/11/2015 05:39 AM"/>
    <a:grammars>
        <a:include href="application.wadl/xsd0.xsd"><a:doc title="Generated" xml:lang="en"/></a:include>
    </a:grammars>
    <a:resources base="http://localhost:9080/rest/">
        <a:resource path="/rmes">
            <a:method id="getRessourcesMetal" name="GET">
                <a:response><a:representation mediaType="application/json"/></a:response>
            </a:method>
            <a:resource path="/{identifiantUm}/{siteUm}"><a:param name="identifiantUm" style="template" xmlns:b="http://www.w3.org/2001/XMLSchema" type="b:string"/><a:param name="siteUm" style="template" xmlns:b="http://www.w3.org/2001/XMLSchema" type="b:string"/>
                <a:method id="get" name="GET">
                    <a:response><a:representation mediaType="application/json"/></a:response>
                </a:method>
                <a:resource path="/categorisations">
                    <a:method id="get" name="GET">
                        <a:response><a:representation mediaType="application/json"/></a:response>
                    </a:method>
                </a:resource>
            </a:resource>
        </a:resource>
        <a:resource path="/Affectation">
            <a:resource path="/articles/{identifiantUm}/{siteUM}"><a:param name="identifiantUm" style="template" xmlns:b="http://www.w3.org/2001/XMLSchema" type="b:string"/><a:param name="siteUM" style="template" xmlns:b="http://www.w3.org/2001/XMLSchema" type="b:string"/>
                <a:method id="rechercherArticle" name="GET">
                    <a:response><a:representation element="bandeauRMVO" mediaType="application/json"/></a:response>
                </a:method>
            </a:resource>
            <a:resource path="/articles">
                <a:method id="rechercherArticle" name="POST">
                    <a:request><a:representation element="resultRechercherArticlePB" mediaType="application/json"/></a:request>
                    <a:response><a:representation element="resultatRechercherArticleVO" mediaType="application/json"/></a:response>
                </a:method>
            </a:resource>
        </a:resource>
        <a:resource path="/apgs">
            <a:resource path="/{numApg: [\p{Alnum}]{1,20}}"><a:param name="numApg" style="template" xmlns:b="http://www.w3.org/2001/XMLSchema" type="b:string"/>
                <a:method id="getApg" name="GET">
                    <a:response><a:representation mediaType="*/*"/></a:response>
                </a:method>
                <a:resource path="/rmes">
                    <a:method id="getRessourcesMetal" name="GET">
                        <a:response><a:representation mediaType="application/json"/></a:response>
                    </a:method>
                    <a:resource path="/{identifiantUm}/{siteUm}"><a:param name="identifiantUm" style="template" xmlns:b="http://www.w3.org/2001/XMLSchema" type="b:string"/><a:param name="siteUm" style="template" xmlns:b="http://www.w3.org/2001/XMLSchema" type="b:string"/>
                        <a:method id="get" name="GET">
                            <a:response><a:representation mediaType="application/json"/></a:response>
                        </a:method>
                        <a:resource path="/categorisations">
                            <a:method id="get" name="GET">
                                <a:response><a:representation mediaType="application/json"/></a:response>
                            </a:method>
                        </a:resource>
                    </a:resource>
                </a:resource>
            </a:resource>
        </a:resource>
    </a:resources>
</a:application>
```

We have corporate proxy, but I cannot see anything relevant in the stack trace.

Thanks for your help

**Comment by IvanGoncharov** [comment]
@nagromc I tried it with snapshot from repo and it works.
Can you please try `npm install --save lucybot/api-spec-converter`?
We will try to release fix ASAP.

**Comment by nagromc** [comment]
Hi @IvanGoncharov and thank you for your quick reply.

I confirm `api-spec-converter` doesn't crash anymore with the snapshot lucybot/api-spec-converter:

```json
{ swagger: '2.0',
  host: 'localhost:9080',
  basePath: '/rest/',
  schemes: [ 'http' ],
  paths:
   { '/rmes': { get: [Object], parameters: [] },
     '/rmes/{identifiantUm}/{siteUm}': { get: [Object], parameters: [Object] },
     '/rmes/{identifiantUm}/{siteUm}/categorisations': { get: [Object], parameters: [Object] },
     '/Affectation/articles/{identifiantUm}/{siteUM}': { get: [Object], parameters: [Object] },
     '/Affectation/articles': { post: [Object], parameters: [] },
     '/apgs/{numApg: [\p{Alnum}]{1,20}}': { get: [Object], parameters: [Object] },
     '/apgs/{numApg: [\p{Alnum}]{1,20}}/rmes': { get: [Object], parameters: [Object] },
     '/apgs/{numApg: [\p{Alnum}]{1,20}}/rmes/{identifiantUm}/{siteUm}': { get: [Object], parameters: [Object] },
     '/apgs/{numApg: [\p{Alnum}]{1,20}}/rmes/{identifiantUm}/{siteUm}/categorisations': { get: [Object], parameters: [Object] }
} }
```

**Comment by IvanGoncharov** [comment]
@nagromc I don't have NPM keys to make release.
But I contacted project owner to ASAP solve this problem.

I also fixed example inside README to use `stringify` method.
So pure JSON is outputted.

**Comment by nagromc** [comment]
@IvanGoncharov Great! Thank you for you support :+1:

**Comment by IvanGoncharov** [comment]
@nagromc Version `1.8.0` released.
